In [10]:
#1
import numpy as np

array = np.array([[1, 6, 3], [4, 5, 6], [7, 88, 9]])

print("Array values:")
print(array)

print("\nShape of the array:")
print(array.shape)
arr_max = np.max(array)
print("maximum mvalue ",arr_max)

Array values:
[[ 1  6  3]
 [ 4  5  6]
 [ 7 88  9]]

Shape of the array:
(3, 3)
maximum mvalue  88


In [7]:
#2
import numpy as np
# a)
my_arr = np.ones((3, 4))

# b)
my_arr += 5

# c)
log_arr = np.log(my_arr)

# d)
arr_mean = np.mean(my_arr)

# e)
arr_std = np.std(my_arr)

# f)
arr_sum = np.sum(my_arr)

# g)
arr_max = np.max(my_arr)

# h)
arr_max_idx = np.argmax(my_arr)

# i)
arr_mean_rows = np.mean(my_arr, axis=1)

# Print all results
print("Array `my_arr` after adding 5 and performing the operations:")
print(my_arr)

print("\nElement-wise logarithm of the array:")
print(log_arr)

print("\nMean of the array:")
print(arr_mean)

print("\nStandard deviation of the array:")
print(arr_std)

print("\nSum of the array:")
print(arr_sum)

print("\nMax value in the array:")
print(arr_max)

print("\nIndex of the max value in the array (flattened index):")
print(arr_max_idx)

print("\nMean along the rows axis of the array:")
print(arr_mean_rows)

Array `my_arr` after adding 5 and performing the operations:
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]

Element-wise logarithm of the array:
[[1.79175947 1.79175947 1.79175947 1.79175947]
 [1.79175947 1.79175947 1.79175947 1.79175947]
 [1.79175947 1.79175947 1.79175947 1.79175947]]

Mean of the array:
6.0

Standard deviation of the array:
0.0

Sum of the array:
72.0

Max value in the array:
6.0

Index of the max value in the array (flattened index):
0

Mean along the rows axis of the array:
[6. 6. 6.]


In [3]:
#3
import numpy as np
my_arr = np.ones((5, 5))

# a)
value = my_arr[3, 1]

#b)
slice_arr = my_arr[0:3, 1:3]

# c)
slice_arr = my_arr[-3:, :]

# d)
slice_arr = my_arr[-3:, :]
slice_arr[:] = -1

print("Original array `my_arr`:")
print(my_arr)

print("\nValue in the fourth row and second column:")
print(value)

print("\nSlice from rows 0 to 2 and columns 1 to 2:")
print(slice_arr)

print("\nArray `my_arr` after updating slice with -1:")
print(my_arr)

Original array `my_arr`:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]

Value in the fourth row and second column:
1.0

Slice from rows 0 to 2 and columns 1 to 2:
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]

Array `my_arr` after updating slice with -1:
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


In [5]:
#4
import numpy as np
my_arr = np.ones((4, 6))

# a)
num_non_zero = np.count_nonzero(my_arr)

# b)
count_elements_axis_0 = my_arr.shape[0]
count_elements_axis_1 = my_arr.shape[1]

# c)
one_d_array = np.array([0, 0, 1, 2, 3, 0, 0])
trimmed_array = np.trim_zeros(one_d_array, 'b')

# d)
reversed_array = np.flip(my_arr)

# e)
square_arr = np.ones((4, 4))
diagonal_sum = np.trace(square_arr)

# f)
matrix_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matrix_sum = np.add(matrix_A, matrix_B)
matrix_diff = np.subtract(matrix_A, matrix_B)

# g)
row_to_add = np.array([10, 10, 10, 10, 10, 10])
expanded_with_row = np.vstack([my_arr, row_to_add])
column_to_add = np.array([10, 10, 10, 10]).reshape(-1, 1)
expanded_with_column = np.hstack([my_arr, column_to_add])

# h)
matrix_mult = np.dot(matrix_A, matrix_B)


print("Original array `my_arr`:")
print(my_arr)

print("\nNumber of non-zero values:")
print(num_non_zero)

print("\nNumber of elements along axis 0:")
print(count_elements_axis_0)

print("\nNumber of elements along axis 1:")
print(count_elements_axis_1)

print("\nTrimmed 1-D array (leading/trailing zeros removed):")
print(trimmed_array)

print("\nReversed array:")
print(reversed_array)

print("\nSum of the diagonal elements:")
print(diagonal_sum)

print("\nMatrix addition result:")
print(matrix_sum)

print("\nMatrix subtraction result:")
print(matrix_diff)

print("\nArray after adding a row:")
print(expanded_with_row)

print("\nArray after adding a column:")
print(expanded_with_column)

print("\nMatrix multiplication result:")
print(matrix_mult)


Original array `my_arr`:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Number of non-zero values:
24

Number of elements along axis 0:
4

Number of elements along axis 1:
6

Trimmed 1-D array (leading/trailing zeros removed):
[0 0 1 2 3]

Reversed array:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Sum of the diagonal elements:
4.0

Matrix addition result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix subtraction result:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Array after adding a row:
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [10. 10. 10. 10. 10. 10.]]

Array after adding a column:
[[ 1.  1.  1.  1.  1.  1. 10.]
 [ 1.  1.  1.  1.  1.  1. 10.]
 [ 1.  1.  1.  1.  1.  1. 10.]
 [ 1.  1.  1.  1.  1.  1. 10.]]

Matrix multiplication result:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [6]:
#5
#a)
import numpy as np
arr = np.array([4, 2, 7, 1, 9])
sorted_indices = np.argsort(arr)

print("Original array:", arr)
print("Indices to sort the array:", sorted_indices)

#b)
import numpy as np
arr = np.array([10, 4, 7, 1, 9, 3])
k = 3
k_smallest = np.partition(arr, k)[:k]

print("Original array:", arr)
print(f"{k} smallest values:", k_smallest)

#c)
import numpy as np
arr = np.array([10, 4, 7, 1, 9, 3])
n = 3
n_largest = np.partition(arr, -n)[-n:]

print("Original array:", arr)
print(f"{n} largest values:", n_largest)

#d)
import numpy as np
matrix = np.array([[4, 2, 7], [1, 9, 3]])
sorted_matrix = np.sort(matrix, axis=None).reshape(matrix.shape)

print("Original matrix:\n", matrix)
print("Sorted matrix:\n", sorted_matrix)

Original array: [4 2 7 1 9]
Indices to sort the array: [3 1 0 2 4]
Original array: [10  4  7  1  9  3]
3 smallest values: [1 3 4]
Original array: [10  4  7  1  9  3]
3 largest values: [ 7  9 10]
Original matrix:
 [[4 2 7]
 [1 9 3]]
Sorted matrix:
 [[1 2 3]
 [4 7 9]]
